### ISSUE TITLE
WASMCLOUD_VERSION=v0.60 Does not work with WADM When Using Private Registry

### ISSUE THREAD

**Issue by stephenandary** [wasmCloud/wadm#41]
When using WADM with a private registry, the host can't be found to deploy providers and actors. 

The same code works fine when using WASMCLOUD_VERSION=v0.59.0.

I have not tested without using a private registry, so that may not be the issue, but I believe @jordan-rash could not recreate with 0.60 without private reg, so it is likely. 

Errors: 
```
17:14:58.444 [error] Failed to perform reconciliation pass: Weighted target 'oauth2_pkce' has insufficient candidate hosts.,
Weighted target 'apigw_router' has insufficient candidate hosts.,
Weighted target 'jammin_messaging_provider_spread' has insufficient candidate hosts.,
Weighted target 'httpclient_spread' has insufficient candidate hosts.,
Weighted target 'httpserver_spread' has insufficient candidate hosts.,
Weighted target 'vault_spread' has insufficient candidate hosts.,
Weighted target 'redis_spread' has insufficient candidate hosts.
```
```
17:15:14.659 [error] GenServer {Wadm.HordeRegistry, "st_default"} terminating
** (FunctionClauseError) no function clause matching in List.foldl/3
    (elixir 1.13.3) lib/list.ex:248: List.foldl(%{}, %LatticeObserver.Observed.Lattice{actors: %{}, claims: %{}, hosts: %{"NA6UITC5DLLNAKTDFYQJRYO3FPAU5RPX64FXKDP46Y7FB74SUTMGT5DX" => %LatticeObserver.Observed.Host{first_seen: ~U[2023-02-22 22:15:14.657009Z], friendly_name: "weathered-fire-6128", id: "NA6UITC5DLLNAKTDFYQJRYO3FPAU5RPX64FXKDP46Y7FB74SUTMGT5DX", labels: %{"app" => "oauth2", "hostcore.arch" => "x86_64", "hostcore.os" => "linux", "hostcore.osfamily" => "unix"}, last_seen: ~U[2023-02-22 22:15:14.657009Z], status: :healthy}}, id: "default", instance_tracking: %{}, invocation_log: %{}, linkdefs: [], parameters: %LatticeObserver.Observed.Lattice.Parameters{host_status_decay_rate_seconds: 35}, providers: %{}, refmap: %{}}, #Function<4.118258543/2 in LatticeObserver.Observed.EventProcessor.record_heartbeat/4>)
    (lattice_observer 0.1.0) lib/lattice_observer/observed/event_processor.ex:198: LatticeObserver.Observed.EventProcessor.record_heartbeat/4
    (wadm 0.2.0) lib/wadm/lattice_state_monitor.ex:36: Wadm.LatticeStateMonitor.handle_info/2
    (stdlib 3.17.2) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.17.2) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:cloud_event, %Cloudevents.Format.V_1_0.Event{data: %{"actors" => %{}, "friendly_name" => "weathered-fire-6128", "labels" => %{"app" => "oauth2", "hostcore.arch" => "x86_64", "hostcore.os" => "linux", "hostcore.osfamily" => "unix"}, "providers" => [], "uptime_human" => "32 seconds", "uptime_seconds" => 32, "version" => "0.60.0"}, datacontenttype: "application/json", dataschema: nil, extensions: %{}, id: "fbdaf2c2-9ae0-42cd-b678-f46c09904ad7", source: "NA6UITC5DLLNAKTDFYQJRYO3FPAU5RPX64FXKDP46Y7FB74SUTMGT5DX", specversion: "1.0", subject: nil, time: "2023-02-22T22:15:14.657009Z", type: "com.wasmcloud.lattice.host_heartbeat"}}
State: %LatticeObserver.Observed.Lattice{actors: %{}, claims: %{}, hosts: %{}, id: "default", instance_tracking: %{}, invocation_log: %{}, linkdefs: [], parameters: %LatticeObserver.Observed.Lattice.Parameters{host_status_decay_rate_seconds: 35}, providers: %{}, refmap: %{}}
```

**Comment by thomastaylor312** [comment]
@stephenandary Because we will be working on #40, it is likely we won't be coming around to fix this (though I won't say never). Wadm isn't currently past alpha-level support yet so I wouldn't depend on it for anything. This will be addressed in the new version though.

**Comment by stephenandary** [comment]
I am using it to bootstrap envs for development currently, I have a ways to go before I will be production ready. This is not a concern for me, just something to note incase others have issues.

**Comment by stephenandary** [comment]
Closing as there is new wadm version now. Can recreate if issue exists still
